name: Deploy to Server

   on:
     push:
       branches:
         - main

   jobs:
     deploy:
       runs-on: ubuntu-latest

       steps:
         - name: Checkout code
           uses: actions/checkout@v2

         - name: Set up SSH
           run: |
             mkdir -p ~/.ssh
             echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
             chmod 600 ~/.ssh/id_rsa
             ssh-keyscan -H 147.45.245.201 >> ~/.ssh/known_hosts

         - name: Create a file on the server
           run: |
             ssh root@147.45.245.201 "echo 'Hello, World!' > /path/to/your/file.txt"