name: Deploy React App

on:
  push:
    branches:
    - main # или другая ветка, с которой вы работаете

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Замените на нужную версию Node.js

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy
      env:
        HOST: ${{ secrets.HOST }} # Адрес вашего сервера
        USER: ${{ secrets.USER }} # Имя пользователя на сервере
        KEY: ${{ secrets.PM2_PRIVATE_KEY }} # SSH ключ для доступа
      run: |
        # Установите ssh-agent
        eval $(ssh-agent -s)
        echo "$KEY" | tr -d '\r' | ssh-add - > /dev/null
        ssh-keyscan -H "$HOST" >> ~/.ssh/known_hosts
        # Копируем собранные файлы на сервер
        rsync -r --delete-after ./build/ $USER@$HOST:/root/_/ui/build
