name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "23.9.0"

      - name: Install dependencies
        run: cd ui && npm install -f

      - name: Build the project
        run: cd ui && npm run build

      - name: Install PM2
        run: npm install -g pm2

      - name: Deploy with PM2
        run: cd ui &&  npm run prod
        env:
          PM2_PUBLIC_KEY: ${{ secrets.PM2_PUBLIC_KEY }}
          PM2_PRIVATE_KEY: ${{ secrets.PM2_PRIVATE_KEY }}
          PM2_APP_ID: ${{ secrets.PM2_APP_ID }}
